springdoc:
  title: Msg urlshortener app
  version: 1.0
  desc: Msg urlshortener app
spring:
  application:
    name: Msg urlshortener app
server:
  port: 9000
db:
  urlshortener:
    hikari:
      url: jdbc:h2:file:../data/urlshortener
      username: sa
      password:
      max-pool-size: 10
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true
      format-sql: true
service:
  urlshortener:
    generateshorturl:
      defaultloop: 500
      redirect:
        scheme: https
        host: adev.avrist.com/st
logging:
  config: classpath:logback-dev.xml